### ISSUE TITLE
Attention scale

### ISSUE THREAD

**Issue by alxndrTL** [KellerJordan/modded-nanogpt#10]
Hello, you use an attention scaling of `(1 / (2 * config.n_layer)**0.5)` to weight the SA term in the `Block` layer.
I'm tried with and without it and it seems to help a bit. (even while keeping the 1/sqrt(2L) init)
I'm curious about where did it come from ? AFAIK classic Transformer implementations (like nanogpt, or the PyTorch one from `llm.c` don't have it)

https://github.com/KellerJordan/modded-nanogpt/blob/ff9661e28be82e924e5c71468d3ea8767df2d9bb/train_gpt2.py#L184C9-L184C58

Thank you

**Comment by KellerJordan** [comment]
Good question. I was trying to match the scale of https://github.com/karpathy/llm.c/blob/7b929300217ff1a974b63791a228928b39b26409/train_gpt2.py#L152 without using a special weight init, which I thought gave better performance. But zero-init of the proj layers, suggested by @Grad62304977, turns out to be even better, so will be switching to that soon
